import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { AppShell } from "@/components/app-shell";
import { RequireAuth } from "@/components/require-auth";
import { getBaselines, runValidation } from "@/lib/api/validation.functions";
import type { MethodId } from "@/lib/validation/simulator";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import {
  DataTable,
  EmptyState,
  ErrorState,
  PageHeader,
  Section,
  SkeletonRows,
  StatusPill,
  Td,
  Tr,
} from "@/components/ui-kit";
import {
  ChartContainer,
  ChartLegend,
  ChartLegendContent,
  ChartTooltip,
  ChartTooltipContent,
  type ChartConfig,
} from "@/components/ui/chart";

export const Route = createFileRoute("/validation")({
  head: () => ({
    meta: [
      { title: "Validation lab — RELI-REF" },
      { name: "description", content: "Controlled simulations comparing the RELI-REF evidence engine against simple baselines on synthetic data." },
      { property: "og:title", content: "Validation lab — RELI-REF" },
      { property: "og:description", content: "Controlled simulations comparing the RELI-REF evidence engine against simple baselines on synthetic data." },
    ],
  }),
  component: () => (
    <RequireAuth>
      <AppShell>
        <ValidationLab />
      </AppShell>
    </RequireAuth>
  ),
});

const chartConfig = {
  top1Success: { label: "Top-1 success rate", color: "var(--ok)" },
} satisfies ChartConfig;

function ValidationLab() {
  const meta = useQuery({ queryKey: ["baselines"], queryFn: () => getBaselines() });
  const [scenario, setScenario] = useState("normal");
  const [seedCount, setSeedCount] = useState(30);
  const [startSeed, setStartSeed] = useState(1);
  const [runsPerSeed, setRunsPerSeed] = useState(3);
  const [methods, setMethods] = useState<Set<MethodId>>(new Set());

  const run = useMutation({
    mutationFn: () =>
      runValidation({
        data: {
          scenario,
          seedCount,
          startSeed,
          runsPerSeed,
          methods: Array.from(methods),
        },
      }),
  });

  const toggleMethod = (id: MethodId) => {
    setMethods((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const candidate = run.data?.results.find((r) => r.method === "reli_ref_sqc");
  const baselines = useMemo(
    () => (run.data?.results ?? []).filter((r) => r.family === "baseline"),
    [run.data],
  );

  const scenarioMeta = (meta.data?.scenarios ?? []).find((s) => s.id === scenario);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Validation lab"
        subtitle="Seeded simulations on synthetic data, used to measure the evidence engine against simple baselines."
      />

      <div className="rounded-md border border-info/30 bg-info-soft px-4 py-3 text-sm text-info">
        <p className="font-medium">This is a controlled simulation, not real-world performance.</p>
        <p className="mt-1 text-info/85">
          Every method here decides against the same synthetic, seeded stream of noisy observations
          generated by the simulator below. Results describe how well each ranking method recovers a
          hidden, simulated ground truth — they do not describe real patients, real facilities, or
          real clinical outcomes.
        </p>
      </div>

      <Section title="Run configuration" description="Every parameter accepted by the simulator is exposed below">
        {meta.isLoading ? (
          <SkeletonRows rows={4} />
        ) : (
          <div className="space-y-5">
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              <div className="space-y-1.5">
                <Label htmlFor="scenario">Scenario</Label>
                <Select value={scenario} onValueChange={setScenario}>
                  <SelectTrigger id="scenario" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {(meta.data?.scenarios ?? []).map((s) => (
                      <SelectItem key={s.id} value={s.id}>{s.label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {scenarioMeta && <p className="text-xs text-muted-foreground">{scenarioMeta.description}</p>}
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="seedCount">Seed count (1–200)</Label>
                <Input
                  id="seedCount"
                  type="number"
                  min={1}
                  max={200}
                  value={seedCount}
                  onChange={(e) => setSeedCount(Number(e.target.value))}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="startSeed">Start seed (1–100000)</Label>
                <Input
                  id="startSeed"
                  type="number"
                  min={1}
                  max={100000}
                  value={startSeed}
                  onChange={(e) => setStartSeed(Number(e.target.value))}
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="runsPerSeed">Runs per seed (1–20)</Label>
                <Input
                  id="runsPerSeed"
                  type="number"
                  min={1}
                  max={20}
                  value={runsPerSeed}
                  onChange={(e) => setRunsPerSeed(Number(e.target.value))}
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <Label>Methods (leave all unchecked to run every method)</Label>
              <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">
                {(meta.data?.methods ?? []).map((m) => (
                  <label key={m.id} className="flex items-center gap-2 rounded-sm border border-border px-2.5 py-1.5 text-sm">
                    <Checkbox checked={methods.has(m.id)} onCheckedChange={() => toggleMethod(m.id)} />
                    <span className="truncate">{m.label}</span>
                  </label>
                ))}
              </div>
            </div>

            <div className="flex items-center gap-3">
              <Button onClick={() => run.mutate()} disabled={run.isPending}>
                {run.isPending ? "Running simulation…" : "Run validation"}
              </Button>
              {run.isPending && <span className="text-sm text-muted-foreground">Simulating {seedCount} seed(s) × {runsPerSeed} run(s)…</span>}
              {run.isError && <span className="text-sm text-danger">{(run.error as Error).message}</span>}
            </div>
          </div>
        )}
      </Section>

      {run.data && (
        <>
          <Section
            title="RELI-REF vs. baselines"
            description={`${run.data.totalRuns} total simulated runs — scenario "${(meta.data?.scenarios ?? []).find((s) => s.id === run.data!.scenario)?.label ?? run.data.scenario}"`}
          >
            <DataTable head={["Method", "Family", "Top-1 success", "Top-3 success", "Failure rate", "Stale selections", "Avg distance (km)", "Δ vs best baseline"]}>
              {run.data.results.map((r) => {
                const bestBaseline = baselines.length
                  ? Math.max(...baselines.map((b) => b.top1Success))
                  : null;
                const delta = bestBaseline != null ? Math.round((r.top1Success - bestBaseline) * 1000) / 10 : null;
                return (
                  <Tr key={r.method}>
                    <Td className="font-medium">{r.label}</Td>
                    <Td>
                      <StatusPill tone={r.family === "reli-ref" ? "info" : "neutral"}>{r.family}</StatusPill>
                    </Td>
                    <Td className="tabular-nums">{Math.round(r.top1Success * 100)}%</Td>
                    <Td className="tabular-nums">{Math.round(r.top3Success * 100)}%</Td>
                    <Td className="tabular-nums">{Math.round(r.failureRate * 100)}%</Td>
                    <Td className="tabular-nums">{Math.round(r.staleSelections * 100)}%</Td>
                    <Td className="tabular-nums">{r.avgDistanceKm.toFixed(1)}</Td>
                    <Td className="tabular-nums">
                      {delta == null ? (
                        "—"
                      ) : (
                        <span className={delta >= 0 ? "text-ok" : "text-danger"}>
                          {delta >= 0 ? "+" : ""}
                          {delta} pp
                        </span>
                      )}
                    </Td>
                  </Tr>
                );
              })}
            </DataTable>
            {candidate && baselines.length > 0 && (
              <p className="mt-3 text-sm text-muted-foreground">
                The candidate model (S × Q × C) reached {Math.round(candidate.top1Success * 100)}% top-1
                success versus a best baseline of {Math.round(Math.max(...baselines.map((b) => b.top1Success)) * 100)}%
                in this simulated scenario.
              </p>
            )}
          </Section>

          <Section title="Top-1 success rate by method" description="Higher is better — share of runs where the chosen facility was truly available in the simulation">
            <ChartContainer config={chartConfig} className="aspect-auto h-80 w-full">
              <BarChart data={run.data.results.map((r) => ({ name: r.label, top1Success: Math.round(r.top1Success * 100) }))} layout="vertical" accessibilityLayer margin={{ left: 24 }}>
                <CartesianGrid horizontal={false} strokeDasharray="3 3" />
                <XAxis type="number" domain={[0, 100]} tickLine={false} axisLine={false} fontSize={11} label={{ value: "Top-1 success (%)", position: "insideBottom", offset: -4, fontSize: 11 }} />
                <YAxis type="category" dataKey="name" tickLine={false} axisLine={false} fontSize={11} width={190} />
                <ChartTooltip content={<ChartTooltipContent />} />
                <ChartLegend content={<ChartLegendContent />} />
                <Bar dataKey="top1Success" fill="var(--color-top1Success)" radius={[0, 2, 2, 0]} />
              </BarChart>
            </ChartContainer>
          </Section>

          <Section title="Methodology" description="How this run was generated">
            <dl className="grid gap-3 text-sm sm:grid-cols-2 xl:grid-cols-4">
              <div className="rounded-sm border border-border bg-surface-sunken p-3">
                <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Scenario</dt>
                <dd className="mt-1">{scenarioMeta?.label ?? run.data.scenario}</dd>
              </div>
              <div className="rounded-sm border border-border bg-surface-sunken p-3">
                <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Seeds</dt>
                <dd className="mt-1">{run.data.seeds.length} (starting at {run.data.seeds[0]})</dd>
              </div>
              <div className="rounded-sm border border-border bg-surface-sunken p-3">
                <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Runs per seed</dt>
                <dd className="mt-1">{run.data.runsPerSeed}</dd>
              </div>
              <div className="rounded-sm border border-border bg-surface-sunken p-3">
                <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Total runs</dt>
                <dd className="mt-1">{run.data.totalRuns}</dd>
              </div>
            </dl>
            <p className="mt-4 text-sm text-muted-foreground">
              Each run builds a small hidden world of simulated facilities with a true availability
              state that evolves over time, generates a noisy stream of staff-reported observations
              according to the selected scenario's report rate, noise, drop rate and switching
              behaviour, then asks every method to rank facilities from identical observations only.
              Success is measured against the hidden ground truth, which no method can see directly.
            </p>
            <p className="mt-2 text-xs text-muted-foreground">
              Reproducibility: every seed uses a deterministic pseudo-random generator (mulberry32),
              so re-running this exact scenario, seed range and run count reproduces identical results.
              Generated at {new Date(run.data.generatedAt).toLocaleString()}.
            </p>
          </Section>
        </>
      )}

      {!run.data && !run.isPending && !run.isError && (
        <EmptyState title="No validation run yet" body="Configure parameters above and run a validation to see comparative results." />
      )}
      {run.isError && <ErrorState message={(run.error as Error).message} retry={() => run.mutate()} />}
    </div>
  );
}
